services:
  web:
    image: nginx:latest
    container_name: kashidashi_web
    ports:
      - "80:80"
    expose:
      - 80
      - 9000
    volumes:
      - ./:/var/www/
      - ./.docker/nginx/kashidashi.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  
  db:
    image: mariadb:10.3.36
    container_name: kashidashi_mysql
    volumes:
      - .docker/data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kashidashi

  php:
    build: .docker/php
    container_name: kashidashi_php
    volumes:
      - .:/var/www/
    environment:
      - PHP_IDE_CONFIG=serverName=kashidashi.local
      - PHP_MEMORY_LIMIT=1G
    depends_on:
      - db
    expose:
      - 9000 # x-debug
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kashidashi_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    links:
      - db
    environment:
      PMA_HOSTS: db
